In [ ]:
#Numpy Tutorial

In [1]:
import numpy as np

# A NumPy array in Python is a powerful data structure provided by the numpy library. It is used for working with large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

In [ ]:
arr1 = np.array([3,10,2,30])

In [ ]:
print(arr1)

[ 3 10  2 30]


In [ ]:
arr2 = np.array([[1,2,3],[1,2,3]])

In [ ]:
print(arr2)

[[1 2 3]
 [1 2 3]]


# Useful attributes of Numpy array:-

# In NumPy, the shape attribute of an array returns a tuple representing the dimensions of the array. The shape gives the number of elements in each dimension.

In [ ]:
arr1.shape # Same as np.array([3,10,2,30],np.int64)

(4,)

In [ ]:
arr2.shape #np.array([[1,2,3],[1,2,3]],np.int64)

(2, 3)

# In NumPy, the ndim attribute of an array returns the number of dimensions (or axes) of the array.

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

# In NumPy, dtype stands for "data type," which defines the type of elements stored in a NumPy array.

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2.dtype

dtype('int64')

# In NumPy, the size attribute of an array returns the total number of elements in the array. It multiplies the dimensions of the array to give the count of elements.

In [ ]:
arr1.size

4

In [ ]:
arr2.size

6

# Replacing the value in arr1[1]

In [ ]:
arr1[1] = 5

In [ ]:
print(arr1)

[ 3  5  2 30]


# Replacing the value in arr2[0,1]

In [ ]:
arr2[0,1] = 5

In [ ]:
print(arr2)

[[1 5 3]
 [1 2 3]]


# Array Creation : Conversion from other Python structures

In [ ]:
listarray = np.array([[1,2,3],[5,6,8],[10,20,25]])

In [ ]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  8],
       [10, 20, 25]])

In [ ]:
arr = np.array({10,20,10})

In [ ]:
arr

array({10, 20}, dtype=object)

# Creating Arrays with Specific Values:-
# NumPy provides some built-in functions to create arrays filled with specific values:-

# Zeros Array: An array filled with zeros

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
zeros = np.zeros((2,5),dtype = int)

In [ ]:
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
zeros = np.zeros((2,5),dtype = bool)

In [ ]:
zeros

array([[False, False, False, False, False],
       [False, False, False, False, False]])

# Ones Array: An array filled with ones

In [ ]:
ones = np.ones((2,5))

In [ ]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
ones = np.ones((2,5),dtype = int)

In [ ]:
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
ones = np.ones((2,5),dtype = bool)

In [ ]:
ones

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# In NumPy, arange() is a function used to create a NumPy array with evenly spaced values within a specified interval. It's similar to the built-in range() function in Python, but arange() returns a NumPy array instead of a list.

In [ ]:
arrayrange = np.arange(1,11,2)

In [ ]:
arrayrange

array([1, 3, 5, 7, 9])

# The linspace() function returns an array of evenly spaced values within the specified interval. It is similar to arange() function but instead of a step, it uses a sample number.

In [ ]:
linspace = np.linspace(1,4,4)

In [ ]:
linspace

array([1., 2., 3., 4.])

# In NumPy, the empty() function is used to create an array without initializing its elements to any particular values.

In [ ]:
empty = np.empty((2,3))

In [ ]:
empty

array([[4.87198757e-310, 0.00000000e+000, 6.90210501e-310],
       [6.90214546e-310, 6.90212481e-310, 6.90212480e-310]])

In [ ]:
empty_like = np.empty_like(linspace)

In [ ]:
empty_like

array([1., 2., 3., 4.])

# In NumPy, the identity function used to create a square identity matrix, which is a matrix with 1s on the main diagonal and 0s elsewhere.

In [ ]:
identity = np.identity(10)

In [ ]:
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arrayrange = np.arange(1,11,1)

In [ ]:
arrayrange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# In NumPy, the reshape() function allows you to change the shape of an array without changing its data.

In [ ]:
arrayrange.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arrayrange.reshape(2,1,5)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

# In NumPy, the ravel() function is used to flatten a multi-dimensional array into a 1D array. It returns a flattened view of the input array if possible, otherwise it returns a copy.

In [ ]:
arrayrange.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arrayrange.shape

(10,)

# In NumPy, the flatten() function is used to return a copy of a multi-dimensional array collapsed into a 1D array.

In [ ]:
arrayrange.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# In NumPy, the transpose() function is used to reverse or permute the axes of an array. It changes the orientation of the array by swapping rows and columns, or any axes in multi-dimensional arrays.

In [ ]:
arrayrange = np.arange(1,11).reshape(2,5)

In [ ]:
arrayrange

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arrayrange.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
arrayrange.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# Mathematical Operations Using Numpy

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# In NumPy, the add() function is used to perform element-wise addition of two arrays.

In [ ]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# In NumPy, the subtract() function is used to perform element-wise subtraction between two arrays.

In [ ]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# In NumPy, the multiply() function in NumPy is used to perform element-wise multiplication of two arrays.

In [ ]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr1 @ arr2 #matrices product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# In NumPy, dot() is used to compute the dot product of two arrays. The operation it performs depends on the input types:
# For 1-D arrays (vectors): It computes the inner product of the vectors.
# For 2-D arrays (matrices): It performs matrix multiplication.
# For N-D arrays: It performs a sum product over the last axis of the first array and the second-to-last of the second array.

In [ ]:
np.dot(arr1,arr2) #matrices product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# In NumPy, the max() function is used to find the maximum value in an array or along a specified axis.

In [ ]:
arr1.max()

9

# In NumPy, argmax() is a function that returns the indices of the maximum values along an axis.

In [ ]:
arr1.argmax()

8

In [ ]:
arr2.max()

9

In [ ]:
arr2.argmax()

8

# In NumPy, the min() function is used to find the minimum value in an array or along a specified axis.

In [ ]:
arr1.min()

1

# In NumPy, argmin() is a function that returns the indices of the minimum values along an axis.

In [ ]:
arr1.argmin()

0

In [ ]:
arr2.min()

1

In [ ]:
arr2.argmin()

0

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1.max(axis = 0) #0 represents column

array([7, 8, 9])

In [ ]:
arr1.min(axis = 0)

array([1, 2, 3])

In [ ]:
arr1.max(axis = 1) #1 represents row

array([3, 6, 9])

In [ ]:
arr1.min(axis = 1)

array([1, 4, 7])

# In NumPy, the sum() is used to calculate the sum of array elements over an specified axis.

In [ ]:
np.sum(arr1)

45

In [ ]:
np.sum(arr1,axis = 0)

array([12, 15, 18])

In [ ]:
np.sum(arr1,axis = 1)

array([ 6, 15, 24])

# In NumPy, the mean() function calculates the arithmetic mean of an array.

In [ ]:
np.mean(arr1)

5.0

# In NumPy, you can use the sqrt() function to calculate the square root of each element in an array.

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# In NumPy, the std() function calculates the standard deviation of an array.

In [ ]:
np.std(arr1)

2.581988897471611

# In NumPy, the exp() function calculates the exponential of each element in an array.

In [ ]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# In NumPy, the log() function is used to calculate the natural logarithm (base e) of each element in an array.

In [ ]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Python NumPy array slicing [:]

In [ ]:
arr = np.arange(1,101).reshape(10,10)

In [ ]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
print(arr[0,0])

1


In [ ]:
arr[0,0].ndim #Value is Scalar

0

# arr[rows,columns]

In [ ]:
arr[0] # Printing only one row in 1D Array format.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0].ndim

1

# arr[start row:end row,start column:end column]

In [ ]:
arr[:,0] #Printing only one column in 1D Array format.

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
arr[:,0].ndim

1

In [ ]:
arr[0:1,] #Printing only one row in 2D Array format

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
arr[0:1,].ndim

2

In [ ]:
arr[:,0:1] #Printing only one column in 2D Array format

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
arr[:,0:1].ndim

2

In [ ]:
arr[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [ ]:
arr[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

# Printing all elements in an array in many ways

In [ ]:
arr[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arr[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arr[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# In NumPy, itemsize is an attribute of an ndarray (NumPy array) that returns the size of each element in the array in bytes.

In [ ]:
arr.itemsize

8

# The values stored in array are of 64-bit format. 1 byte = 8 bits

In [ ]:
arr.dtype

dtype('int64')

# Python NumPy Array Contactenation and Split

In [ ]:
arr1 = np.arange(1,101).reshape(10,10)

In [ ]:
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arr2 = np.arange(101,201).reshape(10,10)

In [ ]:
arr2

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175, 176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195, 196, 197, 198, 199, 200]])

In [ ]:
list1 = [1,2,3,4]
list2 = [1,2,3,4]

In [ ]:
list1 + list2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
arr1 + arr2 #Invalid Concatenation in NumPy Array

array([[102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200],
       [202, 204, 206, 208, 210, 212, 214, 216, 218, 220],
       [222, 224, 226, 228, 230, 232, 234, 236, 238, 240],
       [242, 244, 246, 248, 250, 252, 254, 256, 258, 260],
       [262, 264, 266, 268, 270, 272, 274, 276, 278, 280],
       [282, 284, 286, 288, 290, 292, 294, 296, 298, 300]])

# In NumPy, you can use the concatenate() function to join two or more arrays along an existing axis.

In [ ]:
np.concatenate((arr1,arr2))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [ ]:
print(arr1)
print(arr2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]


In [ ]:
np.concatenate((arr1,arr2),axis=0)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [ ]:
np.concatenate((arr1,arr2),axis=1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30, 121, 122, 123,
        124, 125, 126, 127, 128, 129, 130],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80, 171, 172, 173,
        174, 175, 176, 177, 178, 179, 180],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90, 181, 1

# In NumPy, vstack() function is used to stack the sequence the input arrays vertically to make a single array.

In [ ]:
np.vstack((arr1,arr2)) #Same as np.concatenate((arr1,arr2),axis=0)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

# In NumPy, hstack() function is used to stack the sequence the input arrays horizontally to make a single array.

In [ ]:
np.hstack((arr1,arr2)) #np.concatenate((arr1,arr2),axis=1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30, 121, 122, 123,
        124, 125, 126, 127, 128, 129, 130],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80, 171, 172, 173,
        174, 175, 176, 177, 178, 179, 180],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90, 181, 1

In [ ]:
np.vstack((arr1,arr2,arr1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [ ]:
np.hstack((arr1,arr2,arr1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110,   1,   2,   3,   4,   5,   6,
          7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30, 121, 122, 123,
        124, 125, 126, 127, 128, 129, 130,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40, 131, 132, 133,
        134, 135, 136, 137, 138, 139, 140,  31,  32,  33,  34,  35,  36,
         37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150,  41,  42,  43,  44,  45,  46,
         47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160,  51,  52,

In [ ]:
arr1 = np.arange(1,5).reshape(2,2)

In [ ]:
arr1

array([[1, 2],
       [3, 4]])

# In NumPy, the split() function is used to divide an array into multiple sub-arrays along a specified axis.

In [ ]:
np.split(arr1,2,axis=0)

[array([[1, 2]]), array([[3, 4]])]

In [ ]:
np.split(arr1,2,axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [ ]:
list1 = np.split(arr1,2)

In [ ]:
type(list1)

list

In [ ]:
list1[0]

array([[1, 2]])

In [ ]:
type(list1[0])

numpy.ndarray

In [ ]:
arr1 = [1,2,3,4,5]

In [ ]:
arr1

[1, 2, 3, 4, 5]

In [ ]:
np.split(arr1,[2,3])

[array([1, 2]), array([3]), array([4, 5])]

# Find sin(), cos(), tan() using NumPy Trigonometry Functions

# In NumPy, you can calculate the sine of an angle (in radians) using the sin() function.

In [ ]:
np.sin(180)

-0.8011526357338304

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
np.sin(180*np.pi/180) # To find the angle in radian

1.2246467991473532e-16

# In NumPy, you can calculate the cosine of an angle (in radians) using the cos() function.

In [ ]:
np.cos(180)

-0.5984600690578581

In [ ]:
np.cos(90)

-0.4480736161291701

# In NumPy, the tan() function calculates the tangent of each element in an array, where the elements are interpreted as angles in radians.

In [ ]:
np.tan(180)

1.3386902103511544

In [ ]:
np.tan(90)

-1.995200412208242

In [ ]:
x_sin = np.arange(0.0,3*np.pi,0.1)

In [ ]:
x_sin

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4])

In [ ]:
y_sin = np.sin(x_sin)

In [ ]:
y_sin

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ,  0.0168139 ,  0.1165492 ,
        0.21511999,  0.31154136,  0.40484992,  0.49411335,  0.57

# Random Sampling with NumPy

# Python has a built-in module that you can use to make random numbers.

In [ ]:
import random

# In NumPy, the random() function is used to generate random numbers.

In [ ]:
np.random.random(1)

array([0.39514826])

In [ ]:
np.random.random((3,3))

array([[0.058837  , 0.14061884, 0.4255709 ],
       [0.8364183 , 0.45218657, 0.36947744],
       [0.53880598, 0.38970703, 0.42944612]])

# In NumPy, the randint() function is used to generate random integers within a specified range.

In [ ]:
np.random.randint(1,4)

1

In [ ]:
np.random.randint(1,4,(4,4))

array([[2, 2, 2, 3],
       [2, 1, 3, 3],
       [3, 2, 1, 2],
       [2, 1, 3, 2]])

In [ ]:
np.random.randint(1,4,(2,4,4))

array([[[2, 3, 3, 1],
        [1, 3, 1, 2],
        [3, 1, 3, 1],
        [2, 3, 1, 2]],

       [[1, 3, 1, 1],
        [1, 2, 1, 1],
        [1, 3, 1, 3],
        [3, 1, 2, 1]]])

# In NumPy, the seed() function is used to initialize the random number generator. This ensures that you get the same sequence of random numbers every time you run your code with the same seed value.

In [ ]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [ ]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

# In NumPy, the rand() function is used to generate random numbers from a uniform distribution over the interval [0, 1].

In [ ]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [ ]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

# In NumPy, the randn() function is used to generate random numbers from a standard normal distribution (mean 0 and variance 1).

In [ ]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [ ]:
x = [1,2,3,4]

# In NumPy, the choice() function is used to generate a random sample from a given 1-D array-like object.

In [ ]:
np.random.choice(x)

4

In [ ]:
for i in x:
  print(np.random.choice(x))

2
1
1
1


# In NumPy, the permutation() function is used to randomly shuffle the elements of an array or create a random permutation of a range of numbers.

In [ ]:
np.random.permutation(x)

array([3, 4, 2, 1])

# String Operations, Comparision and Information

In [2]:
chname = "Indian AI Production"
str1 = "Learning NumPy Tutorial"

# In NumPy, np.char.add() is a function used to concatenate strings element-wise from two arrays.

In [3]:
np.char.add(chname,str1)

array('Indian AI ProductionLearning NumPy Tutorial', dtype='<U43')

# In NumPy, np.char.lower() is a function used to convert all uppercase characters in a string or an array of strings to lowercase.

In [4]:
np.char.lower(chname)

array('indian ai production', dtype='<U20')

# In NumPy, np.char.upper() is a function used to convert all lowercase characters in a string or an array of strings to uppercase.

In [5]:
np.char.upper(chname)

array('INDIAN AI PRODUCTION', dtype='<U20')

# In NumPy, np.char.center() is a function used to center strings within a specified width, padding them with a given character (defaulting to space).

In [6]:
np.char.center(chname,60,fillchar="*")

array('********************Indian AI Production********************',
      dtype='<U60')

# In NumPy, np.char.split() is a function that splits strings within a NumPy array element-wise, based on a specified delimiter.

In [7]:
np.char.split(chname)

array(list(['Indian', 'AI', 'Production']), dtype=object)

# The np.char.splitlines() function in NumPy is used to split a string or an array of strings into lines based on line boundaries.

In [8]:
np.char.splitlines("Indian\nAI\nProduction")

array(list(['Indian', 'AI', 'Production']), dtype=object)

In [9]:
str3 = "dmy"
str4 = "dmy"

# The np.char.join() function in NumPy is used to concatenate strings within each element of an array using a specified separator.

In [10]:
np.char.join([":","/"],[str3,str4])

array(['d:m:y', 'd/m/y'], dtype='<U5')

# In NumPy, np.char.replace() is a function used to replace occurrences of a substring within each string element of a NumPy array.

In [12]:
np.char.replace(chname,"AI","Artificial Intelligence")

array('Indian Artificial Intelligence Production', dtype='<U41')

# In NumPy, np.char.equal() is a function used to perform element-wise string comparison between two arrays. It returns a boolean array indicating whether the corresponding elements in the two arrays are equal.

In [17]:
np.char.equal(str3,str4)

array(True)

# In NumPy, np.char.count() is a function used to count the occurrences of a specific substring within each element of a string array.

In [19]:
np.char.count(chname,"a")

array(1)

# The np.char.find() function in NumPy is used to find the index of the first occurrence of a substring within each string element of a NumPy array.

In [20]:
np.char.find(chname,"AI")

array(7)